### ISSUE TITLE
请问这个包能否在linux上安装

### ISSUE THREAD

**Issue by Ziyua1998** [Zaoqu-Liu/BioEnricher#1]
作者您好，我尝试在linux的R中运行本地安装的代码，发现报了如下两个错。

![微信截图_20231211190216](https://github.com/Zaoqu-Liu/BioEnricher/assets/45306934/12c6b8c7-f589-4f73-80ad-f9440c917682)

![微信图片_20231211190024](https://github.com/Zaoqu-Liu/BioEnricher/assets/45306934/a60bf170-8adf-46f0-a782-93bda6a8b669)
![微信截图_20231211190540](https://github.com/Zaoqu-Liu/BioEnricher/assets/45306934/7fefc78b-9b89-4006-b762-47b0641d9c5f)

请问这个包只支持windows环境运行，不支持linux吗？

**Comment by Zaoqu-Liu** [comment]
你可以解压缩试一试，应该可以
