### ISSUE TITLE
What species does this apply to

### ISSUE THREAD

**Issue by wolverinelei** [Zaoqu-Liu/BioEnricher#3]
Good job! Thanks for your contribution, i can finish GO or KEGG easier.

But, what species does this apply to?

**Comment by Zaoqu-Liu** [comment]
您已经解决了嘛 我打算明天统一回复并解决朋友们提出的问题



| |
刘灶渠
|
|
***@***.***
|
---- Replied Message ----
| From | Lei ***@***.***> |
| Date | 12/16/2023 13:11 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | Re: [Zaoqu-Liu/BioEnricher] What species does this apply to (Issue #3) |

Closed #3 as completed.

**Comment by wolverinelei** [comment]
再次感谢您做出的工作，这个包确实很好用
是的，我仔细阅读了说明书，发现也可以应用于小鼠，但是不知为什么gsea结果为空，尽管我的差异基因极多。
另外个人觉得或许咱可以添加一个小条件呢，如果物种为小鼠，则CMAP等数据库参数自动为F会不会让人更加方便使用呢

**Comment by Zaoqu-Liu** [comment]
这里除了CMAP，其它都可以进行小鼠和人类的富集分析，当你选择物种为小鼠时，CMAP自动设置为做不了，这个内置功能已经实现


| |
刘灶渠
|
|
***@***.***
|
---- Replied Message ----
| From | Lei ***@***.***> |
| Date | 12/17/2023 11:31 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [Zaoqu-Liu/BioEnricher] What species does this apply to (Issue #3) |

再次感谢您做出的工作，这个包确实很好用
是的，我仔细阅读了说明书，发现也可以应用于小鼠，但是不知为什么gsea结果为空，尽管我的差异基因极多。
另外个人觉得或许咱可以添加一个小条件呢，如果物种为小鼠，则CMAP等数据库参数自动为F会不会让人更加方便使用呢
