### ISSUE TITLE
config R packages problem

### ISSUE THREAD

**Issue by CCCBBG** [Zaoqu-Liu/BioEnricher#5]

**Comment by CCCBBG** [comment]
> _No description provided
shows
Error: ERROR: no packages specified
Warning message:
In install.packages("BioEnricher_0.1.0.zip", repos = NULL, type = "source") :
  installation of package ‘BioEnricher_0.1.0.zip’ had non-zero exit status

**Comment by Zaoqu-Liu** [comment]
解压再安装


| |
Zaoqu Liu
Doctor
|
|
18439932426
***@***.***
Peking Union Medical College
|


---- Replied Message ----
| From | ***@***.***> |
| Date | 12/27/2023 22:27 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | Re: [Zaoqu-Liu/BioEnricher] config R packages problem (Issue #5) |

_No description provided
shows
Error: ERROR: no packages specified
Warning message:
In install.packages("BioEnricher_0.1.0.zip", repos = NULL, type = "source") :
installation of package ‘BioEnricher_0.1.0.zip’ had non-zero exit status

**Comment by CCCBBG** [comment]
哦哦是的，我解决了，
感谢感谢，非常好用

---Original---
From: ***@***.***&gt;
Date: Wed, Dec 27, 2023 22:29 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Zaoqu-Liu/BioEnricher] config R packages problem (Issue #5)




 解压再安装
 
 
 | |
 Zaoqu Liu
 Doctor
 |
 |
 18439932426
 ***@***.***
 Peking Union Medical College
 |
 
 
 ---- Replied Message ----
 | From | ***@***.***&gt; |
 | Date | 12/27/2023 22:27 |
 | To | ***@***.***&gt; |
 | Cc | ***@***.***&gt; |
 | Subject | Re: [Zaoqu-Liu/BioEnricher] config R packages problem (Issue #5) |
 
 _No description provided
 shows
 Error: ERROR: no packages specified
 Warning message:
 In install.packages("BioEnricher_0.1.0.zip", repos = NULL, type = "source") :
 installation of package ‘BioEnricher_0.1.0.zip’ had non-zero exit status
